version: "3.9"

services:
  postgres:
    image: postgres:16.0-alpine3.18
    container_name: ownership_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  fastapi:
    image: ownership_backend:2023.12.18
    container_name: ownership_backend
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - .:/app

volumes:
  postgres_data:
